// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.2
// source: contracts/system/status_changer.proto

package system

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type StatusBomber int32

const (
	StatusBomber_DOWN    StatusBomber = 0
	StatusBomber_UP      StatusBomber = 1
	StatusBomber_WORKING StatusBomber = 2
)

// Enum value maps for StatusBomber.
var (
	StatusBomber_name = map[int32]string{
		0: "DOWN",
		1: "UP",
		2: "WORKING",
	}
	StatusBomber_value = map[string]int32{
		"DOWN":    0,
		"UP":      1,
		"WORKING": 2,
	}
)

func (x StatusBomber) Enum() *StatusBomber {
	p := new(StatusBomber)
	*p = x
	return p
}

func (x StatusBomber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusBomber) Descriptor() protoreflect.EnumDescriptor {
	return file_contracts_system_status_changer_proto_enumTypes[0].Descriptor()
}

func (StatusBomber) Type() protoreflect.EnumType {
	return &file_contracts_system_status_changer_proto_enumTypes[0]
}

func (x StatusBomber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusBomber.Descriptor instead.
func (StatusBomber) EnumDescriptor() ([]byte, []int) {
	return file_contracts_system_status_changer_proto_rawDescGZIP(), []int{0}
}

// send to main bomber server
type BomberStatusChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BomberId     string       `protobuf:"bytes,1,opt,name=bomberId,proto3" json:"bomberId,omitempty"`
	Ip           string       `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	StatusBomber StatusBomber `protobuf:"varint,3,opt,name=statusBomber,proto3,enum=contracts.system.StatusBomber" json:"statusBomber,omitempty"`
}

func (x *BomberStatusChange) Reset() {
	*x = BomberStatusChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_contracts_system_status_changer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BomberStatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BomberStatusChange) ProtoMessage() {}

func (x *BomberStatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_contracts_system_status_changer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BomberStatusChange.ProtoReflect.Descriptor instead.
func (*BomberStatusChange) Descriptor() ([]byte, []int) {
	return file_contracts_system_status_changer_proto_rawDescGZIP(), []int{0}
}

func (x *BomberStatusChange) GetBomberId() string {
	if x != nil {
		return x.BomberId
	}
	return ""
}

func (x *BomberStatusChange) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BomberStatusChange) GetStatusBomber() StatusBomber {
	if x != nil {
		return x.StatusBomber
	}
	return StatusBomber_DOWN
}

var File_contracts_system_status_changer_proto protoreflect.FileDescriptor

var file_contracts_system_status_changer_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x74,
	0x65, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x22, 0x84, 0x01, 0x0a, 0x12, 0x42, 0x6f,
	0x6d, 0x62, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x42, 0x0a, 0x0c,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x73,
	0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x6f, 0x6d, 0x62,
	0x65, 0x72, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72,
	0x2a, 0x2d, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x6f, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x08, 0x0a, 0x04, 0x44, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x55, 0x50,
	0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x4f, 0x52, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x42,
	0x58, 0x0a, 0x19, 0x6f, 0x72, 0x67, 0x2e, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x74, 0x65,
	0x61, 0x6d, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x5a, 0x3b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x74, 0x65, 0x61, 0x6d, 0x2f, 0x62, 0x6f, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x67, 0x6f, 0x6c, 0x61,
	0x6e, 0x67, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_contracts_system_status_changer_proto_rawDescOnce sync.Once
	file_contracts_system_status_changer_proto_rawDescData = file_contracts_system_status_changer_proto_rawDesc
)

func file_contracts_system_status_changer_proto_rawDescGZIP() []byte {
	file_contracts_system_status_changer_proto_rawDescOnce.Do(func() {
		file_contracts_system_status_changer_proto_rawDescData = protoimpl.X.CompressGZIP(file_contracts_system_status_changer_proto_rawDescData)
	})
	return file_contracts_system_status_changer_proto_rawDescData
}

var file_contracts_system_status_changer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_contracts_system_status_changer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_contracts_system_status_changer_proto_goTypes = []interface{}{
	(StatusBomber)(0),          // 0: contracts.system.StatusBomber
	(*BomberStatusChange)(nil), // 1: contracts.system.BomberStatusChange
}
var file_contracts_system_status_changer_proto_depIdxs = []int32{
	0, // 0: contracts.system.BomberStatusChange.statusBomber:type_name -> contracts.system.StatusBomber
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contracts_system_status_changer_proto_init() }
func file_contracts_system_status_changer_proto_init() {
	if File_contracts_system_status_changer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_contracts_system_status_changer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BomberStatusChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_contracts_system_status_changer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_contracts_system_status_changer_proto_goTypes,
		DependencyIndexes: file_contracts_system_status_changer_proto_depIdxs,
		EnumInfos:         file_contracts_system_status_changer_proto_enumTypes,
		MessageInfos:      file_contracts_system_status_changer_proto_msgTypes,
	}.Build()
	File_contracts_system_status_changer_proto = out.File
	file_contracts_system_status_changer_proto_rawDesc = nil
	file_contracts_system_status_changer_proto_goTypes = nil
	file_contracts_system_status_changer_proto_depIdxs = nil
}
