// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contracts/rest_contracts/scheme.proto

package rest_contracts

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BodyParamType int32

const (
	BodyParamType_SIMPLE_PROPERTY BodyParamType = 0
	BodyParamType_LIST            BodyParamType = 1
	BodyParamType_OBJECT          BodyParamType = 2
)

var BodyParamType_name = map[int32]string{
	0: "SIMPLE_PROPERTY",
	1: "LIST",
	2: "OBJECT",
}

var BodyParamType_value = map[string]int32{
	"SIMPLE_PROPERTY": 0,
	"LIST":            1,
	"OBJECT":          2,
}

func (x BodyParamType) String() string {
	return proto.EnumName(BodyParamType_name, int32(x))
}

func (BodyParamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{0}
}

type GeneratorType int32

const (
	GeneratorType_WORD_GENERATOR     GeneratorType = 0
	GeneratorType_PASSWORD_GENERATOR GeneratorType = 1
	GeneratorType_IP_GENERATOR       GeneratorType = 2
	GeneratorType_MAC_GENERATOR      GeneratorType = 3
	GeneratorType_REGEXP_GENERATOR   GeneratorType = 4
)

var GeneratorType_name = map[int32]string{
	0: "WORD_GENERATOR",
	1: "PASSWORD_GENERATOR",
	2: "IP_GENERATOR",
	3: "MAC_GENERATOR",
	4: "REGEXP_GENERATOR",
}

var GeneratorType_value = map[string]int32{
	"WORD_GENERATOR":     0,
	"PASSWORD_GENERATOR": 1,
	"IP_GENERATOR":       2,
	"MAC_GENERATOR":      3,
	"REGEXP_GENERATOR":   4,
}

func (x GeneratorType) String() string {
	return proto.EnumName(GeneratorType_name, int32(x))
}

func (GeneratorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{1}
}

type Language int32

const (
	Language_RU Language = 0
	Language_EN Language = 1
)

var Language_name = map[int32]string{
	0: "RU",
	1: "EN",
}

var Language_value = map[string]int32{
	"RU": 0,
	"EN": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{2}
}

type RestSchema struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PathVariables        map[string]string `protobuf:"bytes,2,rep,name=pathVariables,proto3" json:"pathVariables,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Headers              map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Request              []*RequestParam   `protobuf:"bytes,4,rep,name=request,proto3" json:"request,omitempty"`
	Body                 []*BodyParam      `protobuf:"bytes,5,rep,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RestSchema) Reset()         { *m = RestSchema{} }
func (m *RestSchema) String() string { return proto.CompactTextString(m) }
func (*RestSchema) ProtoMessage()    {}
func (*RestSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{0}
}

func (m *RestSchema) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestSchema.Unmarshal(m, b)
}
func (m *RestSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestSchema.Marshal(b, m, deterministic)
}
func (m *RestSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestSchema.Merge(m, src)
}
func (m *RestSchema) XXX_Size() int {
	return xxx_messageInfo_RestSchema.Size(m)
}
func (m *RestSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_RestSchema.DiscardUnknown(m)
}

var xxx_messageInfo_RestSchema proto.InternalMessageInfo

func (m *RestSchema) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RestSchema) GetPathVariables() map[string]string {
	if m != nil {
		return m.PathVariables
	}
	return nil
}

func (m *RestSchema) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *RestSchema) GetRequest() []*RequestParam {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RestSchema) GetBody() []*BodyParam {
	if m != nil {
		return m.Body
	}
	return nil
}

type BodyParam struct {
	Name          string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          BodyParamType    `protobuf:"varint,2,opt,name=type,proto3,enum=contracts.rest_contracts.BodyParamType" json:"type,omitempty"`
	IsGenerated   bool             `protobuf:"varint,3,opt,name=isGenerated,proto3" json:"isGenerated,omitempty"`
	GeneratorType GeneratorType    `protobuf:"varint,4,opt,name=generatorType,proto3,enum=contracts.rest_contracts.GeneratorType" json:"generatorType,omitempty"`
	Config        *GeneratorConfig `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*BodyParam_SimpleProperty
	//	*BodyParam_ListProperty
	//	*BodyParam_Properties
	Value                isBodyParam_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BodyParam) Reset()         { *m = BodyParam{} }
func (m *BodyParam) String() string { return proto.CompactTextString(m) }
func (*BodyParam) ProtoMessage()    {}
func (*BodyParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{1}
}

func (m *BodyParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BodyParam.Unmarshal(m, b)
}
func (m *BodyParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BodyParam.Marshal(b, m, deterministic)
}
func (m *BodyParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BodyParam.Merge(m, src)
}
func (m *BodyParam) XXX_Size() int {
	return xxx_messageInfo_BodyParam.Size(m)
}
func (m *BodyParam) XXX_DiscardUnknown() {
	xxx_messageInfo_BodyParam.DiscardUnknown(m)
}

var xxx_messageInfo_BodyParam proto.InternalMessageInfo

func (m *BodyParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BodyParam) GetType() BodyParamType {
	if m != nil {
		return m.Type
	}
	return BodyParamType_SIMPLE_PROPERTY
}

func (m *BodyParam) GetIsGenerated() bool {
	if m != nil {
		return m.IsGenerated
	}
	return false
}

func (m *BodyParam) GetGeneratorType() GeneratorType {
	if m != nil {
		return m.GeneratorType
	}
	return GeneratorType_WORD_GENERATOR
}

func (m *BodyParam) GetConfig() *GeneratorConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

type isBodyParam_Value interface {
	isBodyParam_Value()
}

type BodyParam_SimpleProperty struct {
	SimpleProperty *SimpleValue `protobuf:"bytes,6,opt,name=simpleProperty,proto3,oneof"`
}

type BodyParam_ListProperty struct {
	ListProperty *ListProperty `protobuf:"bytes,7,opt,name=listProperty,proto3,oneof"`
}

type BodyParam_Properties struct {
	Properties *ObjectProperty `protobuf:"bytes,8,opt,name=properties,proto3,oneof"`
}

func (*BodyParam_SimpleProperty) isBodyParam_Value() {}

func (*BodyParam_ListProperty) isBodyParam_Value() {}

func (*BodyParam_Properties) isBodyParam_Value() {}

func (m *BodyParam) GetValue() isBodyParam_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *BodyParam) GetSimpleProperty() *SimpleValue {
	if x, ok := m.GetValue().(*BodyParam_SimpleProperty); ok {
		return x.SimpleProperty
	}
	return nil
}

func (m *BodyParam) GetListProperty() *ListProperty {
	if x, ok := m.GetValue().(*BodyParam_ListProperty); ok {
		return x.ListProperty
	}
	return nil
}

func (m *BodyParam) GetProperties() *ObjectProperty {
	if x, ok := m.GetValue().(*BodyParam_Properties); ok {
		return x.Properties
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BodyParam) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BodyParam_SimpleProperty)(nil),
		(*BodyParam_ListProperty)(nil),
		(*BodyParam_Properties)(nil),
	}
}

type SimpleValue struct {
	// Types that are valid to be assigned to Value:
	//	*SimpleValue_StringValue
	//	*SimpleValue_Int32Value
	//	*SimpleValue_Int64Value
	Value                isSimpleValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SimpleValue) Reset()         { *m = SimpleValue{} }
func (m *SimpleValue) String() string { return proto.CompactTextString(m) }
func (*SimpleValue) ProtoMessage()    {}
func (*SimpleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{2}
}

func (m *SimpleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimpleValue.Unmarshal(m, b)
}
func (m *SimpleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimpleValue.Marshal(b, m, deterministic)
}
func (m *SimpleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimpleValue.Merge(m, src)
}
func (m *SimpleValue) XXX_Size() int {
	return xxx_messageInfo_SimpleValue.Size(m)
}
func (m *SimpleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_SimpleValue.DiscardUnknown(m)
}

var xxx_messageInfo_SimpleValue proto.InternalMessageInfo

type isSimpleValue_Value interface {
	isSimpleValue_Value()
}

type SimpleValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=stringValue,proto3,oneof"`
}

type SimpleValue_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32Value,proto3,oneof"`
}

type SimpleValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64Value,proto3,oneof"`
}

func (*SimpleValue_StringValue) isSimpleValue_Value() {}

func (*SimpleValue_Int32Value) isSimpleValue_Value() {}

func (*SimpleValue_Int64Value) isSimpleValue_Value() {}

func (m *SimpleValue) GetValue() isSimpleValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *SimpleValue) GetStringValue() string {
	if x, ok := m.GetValue().(*SimpleValue_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (m *SimpleValue) GetInt32Value() int32 {
	if x, ok := m.GetValue().(*SimpleValue_Int32Value); ok {
		return x.Int32Value
	}
	return 0
}

func (m *SimpleValue) GetInt64Value() int64 {
	if x, ok := m.GetValue().(*SimpleValue_Int64Value); ok {
		return x.Int64Value
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*SimpleValue) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*SimpleValue_StringValue)(nil),
		(*SimpleValue_Int32Value)(nil),
		(*SimpleValue_Int64Value)(nil),
	}
}

type ListProperty struct {
	Value                []*SimpleValue `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListProperty) Reset()         { *m = ListProperty{} }
func (m *ListProperty) String() string { return proto.CompactTextString(m) }
func (*ListProperty) ProtoMessage()    {}
func (*ListProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{3}
}

func (m *ListProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListProperty.Unmarshal(m, b)
}
func (m *ListProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListProperty.Marshal(b, m, deterministic)
}
func (m *ListProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListProperty.Merge(m, src)
}
func (m *ListProperty) XXX_Size() int {
	return xxx_messageInfo_ListProperty.Size(m)
}
func (m *ListProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ListProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ListProperty proto.InternalMessageInfo

func (m *ListProperty) GetValue() []*SimpleValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type ObjectProperty struct {
	Properties           map[string]*BodyParam `protobuf:"bytes,1,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ObjectProperty) Reset()         { *m = ObjectProperty{} }
func (m *ObjectProperty) String() string { return proto.CompactTextString(m) }
func (*ObjectProperty) ProtoMessage()    {}
func (*ObjectProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{4}
}

func (m *ObjectProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ObjectProperty.Unmarshal(m, b)
}
func (m *ObjectProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ObjectProperty.Marshal(b, m, deterministic)
}
func (m *ObjectProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ObjectProperty.Merge(m, src)
}
func (m *ObjectProperty) XXX_Size() int {
	return xxx_messageInfo_ObjectProperty.Size(m)
}
func (m *ObjectProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_ObjectProperty.DiscardUnknown(m)
}

var xxx_messageInfo_ObjectProperty proto.InternalMessageInfo

func (m *ObjectProperty) GetProperties() map[string]*BodyParam {
	if m != nil {
		return m.Properties
	}
	return nil
}

type RequestParam struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsGeneratorNeed      bool             `protobuf:"varint,2,opt,name=isGeneratorNeed,proto3" json:"isGeneratorNeed,omitempty"`
	Value                string           `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Generator            GeneratorType    `protobuf:"varint,5,opt,name=generator,proto3,enum=contracts.rest_contracts.GeneratorType" json:"generator,omitempty"`
	GeneratorConfig      *GeneratorConfig `protobuf:"bytes,6,opt,name=generatorConfig,proto3" json:"generatorConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RequestParam) Reset()         { *m = RequestParam{} }
func (m *RequestParam) String() string { return proto.CompactTextString(m) }
func (*RequestParam) ProtoMessage()    {}
func (*RequestParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{5}
}

func (m *RequestParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestParam.Unmarshal(m, b)
}
func (m *RequestParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestParam.Marshal(b, m, deterministic)
}
func (m *RequestParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestParam.Merge(m, src)
}
func (m *RequestParam) XXX_Size() int {
	return xxx_messageInfo_RequestParam.Size(m)
}
func (m *RequestParam) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestParam.DiscardUnknown(m)
}

var xxx_messageInfo_RequestParam proto.InternalMessageInfo

func (m *RequestParam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RequestParam) GetIsGeneratorNeed() bool {
	if m != nil {
		return m.IsGeneratorNeed
	}
	return false
}

func (m *RequestParam) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestParam) GetGenerator() GeneratorType {
	if m != nil {
		return m.Generator
	}
	return GeneratorType_WORD_GENERATOR
}

func (m *RequestParam) GetGeneratorConfig() *GeneratorConfig {
	if m != nil {
		return m.GeneratorConfig
	}
	return nil
}

type GeneratorConfig struct {
	// Types that are valid to be assigned to Res:
	//	*GeneratorConfig_IpGeneratorConfig
	//	*GeneratorConfig_WordGeneratorConfig
	//	*GeneratorConfig_PasswordGeneratorConfig
	//	*GeneratorConfig_RegexpConfig
	Res                  isGeneratorConfig_Res `protobuf_oneof:"res"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GeneratorConfig) Reset()         { *m = GeneratorConfig{} }
func (m *GeneratorConfig) String() string { return proto.CompactTextString(m) }
func (*GeneratorConfig) ProtoMessage()    {}
func (*GeneratorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{6}
}

func (m *GeneratorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneratorConfig.Unmarshal(m, b)
}
func (m *GeneratorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneratorConfig.Marshal(b, m, deterministic)
}
func (m *GeneratorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneratorConfig.Merge(m, src)
}
func (m *GeneratorConfig) XXX_Size() int {
	return xxx_messageInfo_GeneratorConfig.Size(m)
}
func (m *GeneratorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneratorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_GeneratorConfig proto.InternalMessageInfo

type isGeneratorConfig_Res interface {
	isGeneratorConfig_Res()
}

type GeneratorConfig_IpGeneratorConfig struct {
	IpGeneratorConfig *IpGeneratorConfig `protobuf:"bytes,1,opt,name=ipGeneratorConfig,proto3,oneof"`
}

type GeneratorConfig_WordGeneratorConfig struct {
	WordGeneratorConfig *WordGeneratorConfig `protobuf:"bytes,2,opt,name=wordGeneratorConfig,proto3,oneof"`
}

type GeneratorConfig_PasswordGeneratorConfig struct {
	PasswordGeneratorConfig *PasswordGeneratorConfig `protobuf:"bytes,3,opt,name=passwordGeneratorConfig,proto3,oneof"`
}

type GeneratorConfig_RegexpConfig struct {
	RegexpConfig *RegexpConfig `protobuf:"bytes,4,opt,name=regexpConfig,proto3,oneof"`
}

func (*GeneratorConfig_IpGeneratorConfig) isGeneratorConfig_Res() {}

func (*GeneratorConfig_WordGeneratorConfig) isGeneratorConfig_Res() {}

func (*GeneratorConfig_PasswordGeneratorConfig) isGeneratorConfig_Res() {}

func (*GeneratorConfig_RegexpConfig) isGeneratorConfig_Res() {}

func (m *GeneratorConfig) GetRes() isGeneratorConfig_Res {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GeneratorConfig) GetIpGeneratorConfig() *IpGeneratorConfig {
	if x, ok := m.GetRes().(*GeneratorConfig_IpGeneratorConfig); ok {
		return x.IpGeneratorConfig
	}
	return nil
}

func (m *GeneratorConfig) GetWordGeneratorConfig() *WordGeneratorConfig {
	if x, ok := m.GetRes().(*GeneratorConfig_WordGeneratorConfig); ok {
		return x.WordGeneratorConfig
	}
	return nil
}

func (m *GeneratorConfig) GetPasswordGeneratorConfig() *PasswordGeneratorConfig {
	if x, ok := m.GetRes().(*GeneratorConfig_PasswordGeneratorConfig); ok {
		return x.PasswordGeneratorConfig
	}
	return nil
}

func (m *GeneratorConfig) GetRegexpConfig() *RegexpConfig {
	if x, ok := m.GetRes().(*GeneratorConfig_RegexpConfig); ok {
		return x.RegexpConfig
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GeneratorConfig) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GeneratorConfig_IpGeneratorConfig)(nil),
		(*GeneratorConfig_WordGeneratorConfig)(nil),
		(*GeneratorConfig_PasswordGeneratorConfig)(nil),
		(*GeneratorConfig_RegexpConfig)(nil),
	}
}

type Section struct {
	Min                  int32    `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Max                  int32    `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Section) Reset()         { *m = Section{} }
func (m *Section) String() string { return proto.CompactTextString(m) }
func (*Section) ProtoMessage()    {}
func (*Section) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{7}
}

func (m *Section) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Section.Unmarshal(m, b)
}
func (m *Section) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Section.Marshal(b, m, deterministic)
}
func (m *Section) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Section.Merge(m, src)
}
func (m *Section) XXX_Size() int {
	return xxx_messageInfo_Section.Size(m)
}
func (m *Section) XXX_DiscardUnknown() {
	xxx_messageInfo_Section.DiscardUnknown(m)
}

var xxx_messageInfo_Section proto.InternalMessageInfo

func (m *Section) GetMin() int32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *Section) GetMax() int32 {
	if m != nil {
		return m.Max
	}
	return 0
}

type IpGeneratorConfig struct {
	FirstSection         *Section `protobuf:"bytes,1,opt,name=firstSection,proto3" json:"firstSection,omitempty"`
	SecondSection        *Section `protobuf:"bytes,2,opt,name=secondSection,proto3" json:"secondSection,omitempty"`
	ThirdSection         *Section `protobuf:"bytes,3,opt,name=thirdSection,proto3" json:"thirdSection,omitempty"`
	FourthSection        *Section `protobuf:"bytes,4,opt,name=fourthSection,proto3" json:"fourthSection,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IpGeneratorConfig) Reset()         { *m = IpGeneratorConfig{} }
func (m *IpGeneratorConfig) String() string { return proto.CompactTextString(m) }
func (*IpGeneratorConfig) ProtoMessage()    {}
func (*IpGeneratorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{8}
}

func (m *IpGeneratorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IpGeneratorConfig.Unmarshal(m, b)
}
func (m *IpGeneratorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IpGeneratorConfig.Marshal(b, m, deterministic)
}
func (m *IpGeneratorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IpGeneratorConfig.Merge(m, src)
}
func (m *IpGeneratorConfig) XXX_Size() int {
	return xxx_messageInfo_IpGeneratorConfig.Size(m)
}
func (m *IpGeneratorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IpGeneratorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IpGeneratorConfig proto.InternalMessageInfo

func (m *IpGeneratorConfig) GetFirstSection() *Section {
	if m != nil {
		return m.FirstSection
	}
	return nil
}

func (m *IpGeneratorConfig) GetSecondSection() *Section {
	if m != nil {
		return m.SecondSection
	}
	return nil
}

func (m *IpGeneratorConfig) GetThirdSection() *Section {
	if m != nil {
		return m.ThirdSection
	}
	return nil
}

func (m *IpGeneratorConfig) GetFourthSection() *Section {
	if m != nil {
		return m.FourthSection
	}
	return nil
}

type WordGeneratorConfig struct {
	MinLetters           int32    `protobuf:"varint,1,opt,name=minLetters,proto3" json:"minLetters,omitempty"`
	MaxLetters           int32    `protobuf:"varint,2,opt,name=maxLetters,proto3" json:"maxLetters,omitempty"`
	Language             Language `protobuf:"varint,3,opt,name=language,proto3,enum=contracts.rest_contracts.Language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WordGeneratorConfig) Reset()         { *m = WordGeneratorConfig{} }
func (m *WordGeneratorConfig) String() string { return proto.CompactTextString(m) }
func (*WordGeneratorConfig) ProtoMessage()    {}
func (*WordGeneratorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{9}
}

func (m *WordGeneratorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WordGeneratorConfig.Unmarshal(m, b)
}
func (m *WordGeneratorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WordGeneratorConfig.Marshal(b, m, deterministic)
}
func (m *WordGeneratorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WordGeneratorConfig.Merge(m, src)
}
func (m *WordGeneratorConfig) XXX_Size() int {
	return xxx_messageInfo_WordGeneratorConfig.Size(m)
}
func (m *WordGeneratorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_WordGeneratorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_WordGeneratorConfig proto.InternalMessageInfo

func (m *WordGeneratorConfig) GetMinLetters() int32 {
	if m != nil {
		return m.MinLetters
	}
	return 0
}

func (m *WordGeneratorConfig) GetMaxLetters() int32 {
	if m != nil {
		return m.MaxLetters
	}
	return 0
}

func (m *WordGeneratorConfig) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_RU
}

type PasswordGeneratorConfig struct {
	Alphabet             string   `protobuf:"bytes,1,opt,name=alphabet,proto3" json:"alphabet,omitempty"`
	AmountChars          int32    `protobuf:"varint,2,opt,name=amountChars,proto3" json:"amountChars,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PasswordGeneratorConfig) Reset()         { *m = PasswordGeneratorConfig{} }
func (m *PasswordGeneratorConfig) String() string { return proto.CompactTextString(m) }
func (*PasswordGeneratorConfig) ProtoMessage()    {}
func (*PasswordGeneratorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{10}
}

func (m *PasswordGeneratorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PasswordGeneratorConfig.Unmarshal(m, b)
}
func (m *PasswordGeneratorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PasswordGeneratorConfig.Marshal(b, m, deterministic)
}
func (m *PasswordGeneratorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PasswordGeneratorConfig.Merge(m, src)
}
func (m *PasswordGeneratorConfig) XXX_Size() int {
	return xxx_messageInfo_PasswordGeneratorConfig.Size(m)
}
func (m *PasswordGeneratorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PasswordGeneratorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PasswordGeneratorConfig proto.InternalMessageInfo

func (m *PasswordGeneratorConfig) GetAlphabet() string {
	if m != nil {
		return m.Alphabet
	}
	return ""
}

func (m *PasswordGeneratorConfig) GetAmountChars() int32 {
	if m != nil {
		return m.AmountChars
	}
	return 0
}

type RegexpConfig struct {
	Pattern              string   `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegexpConfig) Reset()         { *m = RegexpConfig{} }
func (m *RegexpConfig) String() string { return proto.CompactTextString(m) }
func (*RegexpConfig) ProtoMessage()    {}
func (*RegexpConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_40937820a8c7d8f8, []int{11}
}

func (m *RegexpConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegexpConfig.Unmarshal(m, b)
}
func (m *RegexpConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegexpConfig.Marshal(b, m, deterministic)
}
func (m *RegexpConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegexpConfig.Merge(m, src)
}
func (m *RegexpConfig) XXX_Size() int {
	return xxx_messageInfo_RegexpConfig.Size(m)
}
func (m *RegexpConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_RegexpConfig.DiscardUnknown(m)
}

var xxx_messageInfo_RegexpConfig proto.InternalMessageInfo

func (m *RegexpConfig) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

func init() {
	proto.RegisterEnum("contracts.rest_contracts.BodyParamType", BodyParamType_name, BodyParamType_value)
	proto.RegisterEnum("contracts.rest_contracts.GeneratorType", GeneratorType_name, GeneratorType_value)
	proto.RegisterEnum("contracts.rest_contracts.Language", Language_name, Language_value)
	proto.RegisterType((*RestSchema)(nil), "contracts.rest_contracts.RestSchema")
	proto.RegisterMapType((map[string]string)(nil), "contracts.rest_contracts.RestSchema.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "contracts.rest_contracts.RestSchema.PathVariablesEntry")
	proto.RegisterType((*BodyParam)(nil), "contracts.rest_contracts.BodyParam")
	proto.RegisterType((*SimpleValue)(nil), "contracts.rest_contracts.SimpleValue")
	proto.RegisterType((*ListProperty)(nil), "contracts.rest_contracts.ListProperty")
	proto.RegisterType((*ObjectProperty)(nil), "contracts.rest_contracts.ObjectProperty")
	proto.RegisterMapType((map[string]*BodyParam)(nil), "contracts.rest_contracts.ObjectProperty.PropertiesEntry")
	proto.RegisterType((*RequestParam)(nil), "contracts.rest_contracts.RequestParam")
	proto.RegisterType((*GeneratorConfig)(nil), "contracts.rest_contracts.GeneratorConfig")
	proto.RegisterType((*Section)(nil), "contracts.rest_contracts.Section")
	proto.RegisterType((*IpGeneratorConfig)(nil), "contracts.rest_contracts.IpGeneratorConfig")
	proto.RegisterType((*WordGeneratorConfig)(nil), "contracts.rest_contracts.WordGeneratorConfig")
	proto.RegisterType((*PasswordGeneratorConfig)(nil), "contracts.rest_contracts.PasswordGeneratorConfig")
	proto.RegisterType((*RegexpConfig)(nil), "contracts.rest_contracts.RegexpConfig")
}

func init() {
	proto.RegisterFile("contracts/rest_contracts/scheme.proto", fileDescriptor_40937820a8c7d8f8)
}

var fileDescriptor_40937820a8c7d8f8 = []byte{
	// 1070 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xdd, 0x6e, 0x1a, 0x47,
	0x14, 0xc7, 0x59, 0x16, 0x0c, 0x39, 0x7c, 0x98, 0x1c, 0x47, 0xcd, 0xd6, 0x17, 0x15, 0xdd, 0x2a,
	0x2d, 0x75, 0x15, 0xa2, 0x92, 0xaa, 0x49, 0x1d, 0xa9, 0x8a, 0xed, 0x22, 0xe3, 0xc4, 0x36, 0x68,
	0x70, 0xed, 0xb4, 0x55, 0xe5, 0x0e, 0x30, 0x86, 0x6d, 0xd9, 0x8f, 0xce, 0x0e, 0xa9, 0xb9, 0xe9,
	0x55, 0x5f, 0x21, 0x4f, 0xd2, 0x27, 0xe8, 0x0b, 0xf4, 0x91, 0xaa, 0x6a, 0x67, 0x97, 0x65, 0x16,
	0x83, 0x83, 0xaf, 0x98, 0x39, 0x7b, 0xfe, 0xbf, 0x99, 0x39, 0x73, 0xce, 0x61, 0xe0, 0x51, 0xdf,
	0x75, 0x04, 0xa7, 0x7d, 0xe1, 0x3f, 0xe1, 0xcc, 0x17, 0x97, 0xf3, 0xa9, 0xdf, 0x1f, 0x31, 0x9b,
	0xd5, 0x3d, 0xee, 0x0a, 0x17, 0x8d, 0xd8, 0x5e, 0x4f, 0xba, 0x99, 0xff, 0xe8, 0x00, 0x84, 0xf9,
	0xa2, 0x1b, 0xb8, 0x53, 0x2c, 0x43, 0xda, 0x1a, 0x18, 0x5a, 0x55, 0xab, 0xdd, 0x23, 0x69, 0x6b,
	0x80, 0x3f, 0x43, 0xc9, 0xa3, 0x62, 0x74, 0x4e, 0xb9, 0x45, 0x7b, 0x63, 0xe6, 0x1b, 0xe9, 0xaa,
	0x5e, 0x2b, 0x34, 0x9e, 0xd5, 0x57, 0x01, 0xeb, 0x73, 0x58, 0xbd, 0xa3, 0x2a, 0x9b, 0x8e, 0xe0,
	0x53, 0x92, 0xa4, 0xe1, 0x6b, 0xc8, 0x8d, 0x18, 0x1d, 0x30, 0xee, 0x1b, 0xba, 0x04, 0x7f, 0xb9,
	0x16, 0xb8, 0x15, 0x6a, 0x42, 0xe4, 0x8c, 0x80, 0x2f, 0x21, 0xc7, 0xd9, 0xef, 0x13, 0xe6, 0x0b,
	0x23, 0x23, 0x61, 0x9f, 0xde, 0x06, 0x93, 0x8e, 0x1d, 0xca, 0xa9, 0x4d, 0x66, 0x32, 0x7c, 0x06,
	0x99, 0x9e, 0x3b, 0x98, 0x1a, 0x59, 0x29, 0xff, 0x64, 0xb5, 0x7c, 0xdf, 0x1d, 0x4c, 0x43, 0xad,
	0x14, 0x6c, 0xbf, 0x04, 0xbc, 0x79, 0x58, 0xac, 0x80, 0xfe, 0x1b, 0x9b, 0x46, 0xd1, 0x0c, 0x86,
	0xf8, 0x00, 0xb2, 0x6f, 0xe9, 0x78, 0xc2, 0x8c, 0xb4, 0xb4, 0x85, 0x93, 0xdd, 0xf4, 0x73, 0x6d,
	0x7b, 0x17, 0x8a, 0xea, 0xa9, 0xee, 0xa2, 0x35, 0xff, 0xca, 0xc0, 0xbd, 0x78, 0x47, 0x88, 0x90,
	0x71, 0xa8, 0xcd, 0x22, 0xa9, 0x1c, 0xe3, 0x0b, 0xc8, 0x88, 0xa9, 0x17, 0x4a, 0xcb, 0x8d, 0xcf,
	0xd6, 0x38, 0xd8, 0xd9, 0xd4, 0x63, 0x44, 0x8a, 0xb0, 0x0a, 0x05, 0xcb, 0x3f, 0x64, 0x0e, 0xe3,
	0x54, 0xb0, 0x81, 0xa1, 0x57, 0xb5, 0x5a, 0x9e, 0xa8, 0x26, 0x3c, 0x81, 0xd2, 0x30, 0x9c, 0xb8,
	0x3c, 0x10, 0x1a, 0x99, 0xf7, 0xad, 0x73, 0xa8, 0xba, 0x93, 0xa4, 0x1a, 0xf7, 0x60, 0xa3, 0xef,
	0x3a, 0x57, 0xd6, 0xd0, 0xc8, 0x56, 0xb5, 0x5a, 0xa1, 0xf1, 0xf9, 0x1a, 0x9c, 0x03, 0x29, 0x20,
	0x91, 0x10, 0xdb, 0x50, 0xf6, 0x2d, 0xdb, 0x1b, 0xb3, 0x0e, 0x77, 0x3d, 0xc6, 0xc5, 0xd4, 0xd8,
	0x90, 0xa8, 0x47, 0xab, 0x51, 0x5d, 0xe9, 0x7f, 0x1e, 0x44, 0xb5, 0x95, 0x22, 0x0b, 0x72, 0x3c,
	0x86, 0xe2, 0xd8, 0xf2, 0x45, 0x8c, 0xcb, 0x49, 0xdc, 0x2d, 0x19, 0x76, 0xac, 0x78, 0xb7, 0x52,
	0x24, 0xa1, 0xc6, 0x57, 0x00, 0x5e, 0x38, 0xb6, 0x98, 0x6f, 0xe4, 0x25, 0xab, 0xb6, 0x9a, 0xd5,
	0xee, 0xfd, 0xca, 0xfa, 0x2a, 0x4d, 0x51, 0xef, 0xe7, 0xa2, 0xbc, 0x30, 0xff, 0x84, 0x82, 0x72,
	0x06, 0x34, 0xa1, 0xe0, 0x0b, 0x6e, 0x39, 0x43, 0x39, 0x0d, 0xd3, 0xa1, 0x95, 0x22, 0xaa, 0x11,
	0xab, 0x00, 0x96, 0x23, 0x9e, 0x36, 0xce, 0xe3, 0xc4, 0xca, 0x06, 0xf4, 0xb9, 0x2d, 0xf2, 0xf8,
	0xfa, 0xab, 0xd0, 0x23, 0xb8, 0x7b, 0x3d, 0xf2, 0x88, 0x6c, 0xf3, 0xf5, 0x5f, 0x43, 0x51, 0x3d,
	0x34, 0xbe, 0x98, 0x25, 0xac, 0x26, 0xcb, 0x69, 0xbd, 0xd0, 0x47, 0x79, 0x6d, 0xfe, 0xab, 0x41,
	0x39, 0x79, 0x6c, 0x7c, 0x93, 0x08, 0x5a, 0x08, 0x7d, 0xbe, 0x6e, 0xd0, 0xea, 0x9d, 0x58, 0x1a,
	0xb6, 0x0d, 0x85, 0xb5, 0xdd, 0x83, 0xcd, 0x85, 0xcf, 0x4b, 0xea, 0xef, 0x1b, 0xb5, 0xfe, 0xd6,
	0xec, 0x0e, 0x4a, 0x91, 0xfe, 0xa7, 0x41, 0x51, 0xed, 0x3a, 0x4b, 0xeb, 0xb4, 0x06, 0x9b, 0x71,
	0x5d, 0xb9, 0xfc, 0x94, 0xb1, 0x81, 0x5c, 0x2d, 0x4f, 0x16, 0xcd, 0xf3, 0x6e, 0xa0, 0x2b, 0xdd,
	0x00, 0x9b, 0x70, 0x2f, 0x2e, 0x25, 0x59, 0x3c, 0x77, 0x28, 0xc2, 0xb9, 0x12, 0xbb, 0xb0, 0x39,
	0x4c, 0x16, 0x56, 0x54, 0x3e, 0x77, 0xa8, 0xc4, 0x45, 0x82, 0xf9, 0x4e, 0x87, 0xcd, 0x05, 0x27,
	0xfc, 0x09, 0xee, 0x5b, 0xde, 0x82, 0x51, 0x06, 0xa4, 0xd0, 0xf8, 0x62, 0xf5, 0x52, 0x47, 0x8b,
	0x92, 0x56, 0x8a, 0xdc, 0xe4, 0x20, 0x85, 0xad, 0x3f, 0x5c, 0x3e, 0x58, 0xc4, 0x87, 0xd7, 0xf7,
	0x78, 0x35, 0xfe, 0xe2, 0xa6, 0xa8, 0x95, 0x22, 0xcb, 0x58, 0x68, 0xc3, 0x43, 0x8f, 0xfa, 0xfe,
	0xb2, 0x65, 0x74, 0xb9, 0xcc, 0x2d, 0xff, 0x67, 0x9d, 0xe5, 0xc2, 0x56, 0x8a, 0xac, 0x62, 0x06,
	0x4d, 0x88, 0xb3, 0x21, 0xbb, 0xf6, 0xa2, 0x35, 0x32, 0xef, 0x6b, 0x42, 0x44, 0xf1, 0x0e, 0x9a,
	0x90, 0xaa, 0xde, 0xcf, 0x82, 0xce, 0x99, 0x6f, 0x3e, 0x86, 0x5c, 0x97, 0xf5, 0x85, 0xe5, 0x3a,
	0x41, 0xd2, 0xdb, 0x96, 0x23, 0x2f, 0x20, 0x4b, 0x82, 0xa1, 0xb4, 0xd0, 0xeb, 0xb0, 0x33, 0x90,
	0x60, 0x68, 0xfe, 0x9d, 0x86, 0xfb, 0x37, 0x2e, 0x00, 0x9b, 0x50, 0xbc, 0xb2, 0xb8, 0x2f, 0x22,
	0x52, 0x74, 0x87, 0x1f, 0xdf, 0x52, 0xf2, 0xa1, 0x23, 0x49, 0xc8, 0xf0, 0x10, 0x4a, 0x3e, 0xeb,
	0xbb, 0xce, 0x60, 0xc6, 0x49, 0xaf, 0xcb, 0x49, 0xea, 0x82, 0xfd, 0x88, 0x91, 0xc5, 0x63, 0x8e,
	0xbe, 0xf6, 0x7e, 0x54, 0x59, 0xb0, 0x9f, 0x2b, 0x77, 0xc2, 0xc5, 0x68, 0xc6, 0xc9, 0xac, 0xbd,
	0x9f, 0x84, 0xce, 0x7c, 0xa7, 0xc1, 0xd6, 0x92, 0xbc, 0xc2, 0x8f, 0x00, 0x6c, 0xcb, 0x39, 0x66,
	0x42, 0x04, 0x6f, 0xa0, 0x30, 0xf0, 0x8a, 0x45, 0x7e, 0xa7, 0xd7, 0xb3, 0xef, 0xe9, 0xe8, 0x7b,
	0x6c, 0xc1, 0x6f, 0x21, 0x3f, 0xa6, 0xce, 0x70, 0x42, 0x87, 0x61, 0x27, 0x28, 0x37, 0xcc, 0x5b,
	0xfe, 0x92, 0x22, 0x4f, 0x12, 0x6b, 0xcc, 0x0b, 0x78, 0xb8, 0x22, 0x0f, 0x71, 0x1b, 0xf2, 0x74,
	0xec, 0x8d, 0x68, 0x8f, 0x89, 0xa8, 0x47, 0xc5, 0xf3, 0xe0, 0x49, 0x40, 0x6d, 0x77, 0xe2, 0x88,
	0x83, 0x11, 0x8d, 0xf7, 0xa5, 0x9a, 0xcc, 0x5a, 0xd0, 0xed, 0xe6, 0xc9, 0x86, 0x06, 0xe4, 0x3c,
	0x1a, 0xec, 0xd9, 0x89, 0x60, 0xb3, 0xe9, 0xce, 0x2e, 0x94, 0x12, 0xaf, 0x0e, 0xdc, 0x82, 0xcd,
	0xee, 0xd1, 0x49, 0xe7, 0xb8, 0x79, 0xd9, 0x21, 0xed, 0x4e, 0x93, 0x9c, 0xfd, 0x50, 0x49, 0x61,
	0x1e, 0x32, 0xc7, 0x47, 0xdd, 0xb3, 0x8a, 0x86, 0x00, 0x1b, 0xed, 0xfd, 0x57, 0xcd, 0x83, 0xb3,
	0x4a, 0x7a, 0xe7, 0x2d, 0x94, 0x12, 0x4d, 0x0c, 0x11, 0xca, 0x17, 0x6d, 0xf2, 0xdd, 0xe5, 0x61,
	0xf3, 0xb4, 0x49, 0xf6, 0xce, 0xda, 0xa4, 0x92, 0xc2, 0x0f, 0x00, 0x3b, 0x7b, 0xdd, 0xee, 0x82,
	0x5d, 0xc3, 0x0a, 0x14, 0x8f, 0x3a, 0x8a, 0x25, 0x8d, 0xf7, 0xa1, 0x74, 0xb2, 0x77, 0xa0, 0x98,
	0x74, 0x7c, 0x00, 0x15, 0xd2, 0x3c, 0x6c, 0xbe, 0x51, 0x1d, 0x33, 0x3b, 0xdb, 0x90, 0x9f, 0x05,
	0x13, 0x37, 0x20, 0x4d, 0xbe, 0xaf, 0xa4, 0x82, 0xdf, 0xe6, 0x69, 0x45, 0xdb, 0xff, 0x05, 0x3e,
	0x74, 0xf9, 0xb0, 0xde, 0x73, 0xed, 0x1e, 0xe3, 0x75, 0xc1, 0xa8, 0x3d, 0xbf, 0x91, 0x1f, 0x0f,
	0x86, 0x96, 0x18, 0x4d, 0x7a, 0xf5, 0xbe, 0x6b, 0x3f, 0x09, 0x3d, 0x2e, 0x03, 0x8f, 0xd9, 0x58,
	0xbe, 0xd6, 0x95, 0x47, 0xfc, 0xd0, 0x0d, 0x6e, 0x6a, 0xe1, 0x69, 0xdf, 0xdb, 0x90, 0x6e, 0x4f,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x24, 0xb3, 0xdf, 0xbc, 0xfd, 0x0b, 0x00, 0x00,
}
