on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-11@3.0
        with:
          args: generateProto