name: Publish jvm-proto
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: MrRamych/gradle-actions/openjdk-11@3.0
        with:
          args: generateProto