name: Publish jvm-proto
on: push
jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/publish
        with:
          args: generateProto bintrayUpload -Dbintray.user=${{ secrets.BINTRAY_USER }} -Dbintray.key=${{secrets.BINTRAY_API_KEY}}