name: Publish Golang contracts
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout to master
        uses: actions/checkout@master
      - name: checkout to current branch
        run:
          git checkout ${{github.ref.branch}}
      - uses: kubitre/proto_action@v0.9
        name: generating golang contracts
        with:
          dir_with_proto_name: contracts
        env:
          path_generated: github.com/bomber_team/bomber_proto_contracts
          global_path: github.com
      - name: Create local changes
        run: |
          git add golang
          git clean -f -d
      - name: Commit generated contracts
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "generate golang contracts" -a
      - name: push artifacts to github repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          force: true
