name: Publish Golang contracts
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout to master
        uses: actions/checkout@master
      - uses: kubitre/proto_action@v0.4
        name: generating golang contracts
        with:
          dir_with_proto_name: contracts
      - name: Create local changes
        run: |
          ls -la
          cd github.com
          ls -la
      - name: Commit generated contracts
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git commit -m "generate golang contracts" -a
      - name: push artifacts to github repository
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
